name: pathology-virtual-stain-cu128
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.10
  - numpy=1.26.4
  - pillow=11.2.1
  - openslide=4.0.0
  - openslide-python=1.4.2
  - pytorch=2.7.0
  - torchvision=0.22.0
  - torchaudio=2.7.0
  - pytorch-cuda=12.8
  - pip
  - pip:
      - openslide-bin==4.0.0.8
